insert into `upmonth-query-db`.shortcodes (`type`, name, shortcode, category, doc_group_code, `date`, search_shortcuts, synonyms)
values  ('ACTION', 'Contributed', 'CNTR', null, null, 'Days', 1, 'Contributed'),
        ('ACTION', 'Favorite', 'FAV', null, null, 'Days', 1, 'Favorite'),
        ('ACTION', 'Modified', 'MOD', null, null, 'Days', 1, 'Modified'),
        ('ACTION', 'More Like This', 'MLT', null, null, null, 1, 'More Like This'),
        ('ACTION', 'Read', 'READ', null, null, 'Days', 1, 'Read, Opened, Viewed'),
        ('ACTION', 'Shared by you', 'SH', null, null, 'Days', 1, 'Shared by you'),
        ('ACTION', 'Taught', 'TGT', null, null, 'Days', 1, 'Taught'),
        ('Class', 'Commodities', 'COMM', null, null, null, 0, 'Resources'),
        ('Class', 'Equities', 'EQ', null, null, null, 1, 'Equity'),
        ('Class', 'Fixed Income', 'FI', null, null, null, 1, 'Fixed-Income, Credit'),
        ('Class', 'Multi-Asset', 'MTA', null, null, null, 0, 'Multi-Asset'),
        ('Class', 'Other-Asset', 'AC_OTHER', null, null, null, 0, 'Fund-of-Funds'),
        ('Class', 'Real Estate', 'RE', null, null, null, 0, 'Real Estate'),
        ('DATE', 'Document Date', 'D', null, null, 'Days', 1, 'Document Date'),
        ('DATE', 'Effective Date', 'EFF', null, null, 'Months', 1, 'Effective Date'),
        ('DATE', 'Upload', 'U', null, null, 'Days', 1, 'Upload'),
        ('DocGroup', 'Agreements', 'AGR', null, 'AGR', 'Years', 1, null),
        ('DocGroup', 'Compliance', 'CPL', null, 'CPL', 'Months', 1, null),
        ('DocGroup', 'General', 'GEN', null, 'GEN', 'Months', 1, null),
        ('DocGroup', 'Memos', 'M', null, 'M', 'Months', 1, 'M, Memo'),
        ('DocGroup', 'Miscellaneous', 'MISC-GROUP', null, 'MISC', 'Months', 1, null),
        ('DocGroup', 'Reporting', 'REP', null, 'REP', 'Months', 1, null),
        ('DocGroup', 'Statements', 'STM', null, 'STM', 'Months', 1, null),
        ('DocType', 'Account Statement', 'ACNT', 'Statements', 'STM', 'Months', 0, ' '),
        ('DocType', 'Agenda', 'AGND', 'Memos', 'M', 'Days', 0, null),
        ('DocType', 'Announcement', 'NOTICE', 'General', 'GEN', 'Months', 0, 'NOTICE'),
        ('DocType', 'Annual Report (Audited)', 'A', 'Reporting', 'REPT', 'Years', 1, 'AFS, Audited Financials, Audit Financial Statement, Audited Statement, Audited Statements, Annual Report, Financial Statement, Financial Statements, Audited Report, Audited Financial Statements, A, financial statement, financial statements, audited statements, audits, audited reports, auditor report, auditor''s statement, Annual Report, Annual Statement'),
        ('DocType', 'Appraisal Statement', 'APPRS', 'Statements', 'STM', 'Months', 0, 'Appraisal Report'),
        ('DocType', 'Audit Confirmation', 'ACL', 'Compliance', 'CPL', 'Years', 0, null),
        ('DocType', 'Background Check', 'BCHECK', 'Compliance', 'CPL', 'Years', 0, 'BKGDCH'),
        ('DocType', 'Biographies', 'BIOGR', 'General', 'GEN', 'Months', 0, null),
        ('DocType', 'Board Package', 'BDPKG', 'General', 'GEN', 'Months', 0, null),
        ('DocType', 'Board Resolution', 'BR', 'Agreements', 'AGR', 'Years', 0, 'resolution'),
        ('DocType', 'Capital Call/Distribution', 'STDIS', 'Statements', 'STM', 'Months', 0, 'Capital Call, Capital Distribution, Contribution Notice, Contribution, Distribution Notice, Distribution'),
        ('DocType', 'Compliance Manual', 'CM', 'Compliance', 'CPL', 'Years', 0, null),
        ('DocType', 'Compliance Statement', 'CPSTMT', 'Compliance', 'CPL', 'Months', 0, null),
        ('DocType', 'Consent Letter', 'CSA', 'Agreements', 'AGR', 'Years', 0, null),
        ('DocType', 'Consultant Report', 'CNR', 'General', 'GEN', 'Months', 0, null),
        ('DocType', 'Contract Note', 'CTRN', 'Statements', 'STM', 'Months', 0, null),
        ('DocType', 'Data', 'DTA', 'General', 'GEN', 'Months', 0, 'DTA'),
        ('DocType', 'Decision Memo', 'DECMEM', 'Memos', 'M', 'Months', 0, 'DECM, IRM, PIN, Investment Memo, Recommendation Memo'),
        ('DocType', 'Due Diligence Questionnaire', 'DDQ', 'Compliance', 'CPL', 'Months', 1, 'Operational Due Diligence'),
        ('DocType', 'Email', 'EMAIL', 'General', 'GEN', 'Months', 0, 'e-mail'),
        ('DocType', 'ESG Report', 'ESGREP', 'Compliance', 'CPL', 'Months', 0, null),
        ('DocType', 'Event', 'EVENT', 'General', 'GEN', 'Months', 0, 'EVENT'),
        ('DocType', 'Fact Sheet', 'TS', 'Reporting', 'REPT', 'Months', 1, 'Factsheet, FS, Tearsheet, tear sheet, fact sheet, monthly reporting, monthly report, article, transparency report, transparency, attribution report, attribution, return data, performance report, returns, newsletter'),
        ('DocType', 'Fee Agreement', 'FEEAGR', 'Agreements', 'AGR', 'Years', 0, null),
        ('DocType', 'Fee Calculations', 'FEECALC', 'Compliance', 'CPL', 'Months', 0, null),
        ('DocType', 'Financial Model', 'FMDL', 'General', 'GEN', 'Months', 0, null),
        ('DocType', 'Form 10K/10Q', '10K', 'Compliance', 'CPL', 'Years', 0, '10Q, 10Ks, 10Qs, form 10Ks, form 10Qs'),
        ('DocType', 'Form 13F', '13F', 'Compliance', 'CPL', 'Years', 0, 'form-13F, 13F filings, 13-F Filings, 13-F'),
        ('DocType', 'Form ADV', 'ADV', 'Compliance', 'CPL', 'Years', 0, 'Form ADV Part II, Form ADV Part 2'),
        ('DocType', 'Holdings Report', 'HLDGS', 'Reporting', 'REPT', 'Months', 0, 'holdings, portfolio holdings, holdings statement'),
        ('DocType', 'ILPA Reporting', 'ILPA', 'Reporting', 'REPT', 'Months', 0, 'ILPA Report'),
        ('DocType', 'Incorporation Document', 'INCDOC', 'Agreements', 'AGR', 'Years', 0, 'INCRP, Incorporation Docs'),
        ('DocType', 'Insurance-Policy', 'INSP', 'Agreements', 'AGR', 'Years', 0, 'Insurance-Policies, InsurancePolicy, InsurancePolicies'),
        ('DocType', 'Investment Management Agreement', 'IMA', 'Agreements', 'AGR', 'Years', 0, null),
        ('DocType', 'Invoice', 'INV', 'Statements', 'STM', 'Months', 0, null),
        ('DocType', 'KIID', 'KIID', 'Compliance', 'CPL', 'Months', 0, null),
        ('DocType', 'Letter', 'L', 'Reporting', 'REPT', 'Months', 1, 'Letters, article, monthly letter, quarterly letter, newsletter, quarterly report'),
        ('DocType', 'Limited Partnership Agreement', 'LPA', 'Agreements', 'AGR', 'Years', 0, null),
        ('DocType', 'Management Representation Letter', 'MREP', 'Reporting', 'REPT', 'Years', 0, 'Representation letter, rep letter, '),
        ('DocType', 'Market Value Reconciliation', 'MV', 'Statements', 'STM', 'Months', 0, 'MVREC, valuation, final valuation, performance reports'),
        ('DocType', 'Meeting Minutes', 'MTGMIN', 'Memos', 'M', 'Days', 0, 'Minutes'),
        ('DocType', 'Meeting Notes', 'MTGNOTE', 'Memos', 'M', 'Days', 0, 'Meeting Memo, Meeting Note'),
        ('DocType', 'Miscellaneous/Other', 'MISC-DOC', 'Misc', 'MISC', 'Months', 0, 'Miscellaneous, Misc'),
        ('DocType', 'News', 'NEWS', 'General', 'GEN', 'Months', 0, 'article'),
        ('DocType', 'Non-Disclosure Agreement', 'NDA', 'Agreements', 'AGR', 'Years', 0, 'nondisclosure agreement, non disclosure agreement'),
        ('DocType', 'Note', 'N', 'Memos', 'M', 'Days', 1, null),
        ('DocType', 'Offering Memorandum', 'OM', 'Agreements', 'AGR', 'Years', 1, 'Prospectus, Offering docs, Private Placement Memorandum, Private Placement, PPM, CEM, Confidential Explanatory Memorandum, private placement docs'),
        ('DocType', 'Performance Estimate', 'EST', 'Statements', 'STM', 'Months', 0, 'estimate, estimates, estimated valuation, performance reports, estimated returns'),
        ('DocType', 'Presentation', 'P', 'General', 'GEN', 'Months', 1, 'Slide deck, slidedeck, deck, marketing docs, marketing material, pitch book, pitch books, pitchbook, pitchbooks'),
        ('DocType', 'Press Release', 'PR', 'General', 'GEN', 'Months', 0, 'News'),
        ('DocType', 'Privacy Notice', 'PRIV', 'Compliance', 'CPL', 'Years', 0, 'Privacy Statement'),
        ('DocType', 'Proxy/Voting', 'PROXY', 'Compliance', 'CPL', 'Years', 0, 'Proxy Statement, Shareholder Voting'),
        ('DocType', 'Quarterly Report (Unaudited)', 'UFS', 'Reporting', 'REPT', 'Months', 0, 'Unaudited Financials, Unaudited Financial Statement, Unaudited Statement, Quarterly Statement, Quarterly Report, Quarterly Reports, Unaudited Report'),
        ('DocType', 'Reference Call', 'REFCALL', 'Memos', 'M', 'Months', 0, 'Ref Call, reference call'),
        ('DocType', 'Report', 'R', 'General', 'GEN', 'Months', 1, 'article'),
        ('DocType', 'Returns', 'PERF', 'Reporting', 'REPT', 'Months', 0, 'return data, performance report, performance data, returns'),
        ('DocType', 'RFI/RFP', 'RFIRFP', 'General', 'GEN', 'Months', 0, 'RFI, RFP'),
        ('DocType', 'Risk Report', 'RISK', 'Reporting', 'REPT', 'Months', 0, 'risk report, attribution report, attribution data, attribution report'),
        ('DocType', 'Service Agreement', 'SLA', 'Agreements', 'AGR', 'Years', 0, 'Service agreement'),
        ('DocType', 'Side Letter', 'SIDE', 'Agreements', 'AGR', 'Years', 0, null),
        ('DocType', 'Site Report', 'STREP', 'Reporting', 'REPT', 'Months', 0, null),
        ('DocType', 'Subscription Document', 'SUB', 'Agreements', 'AGR', 'Years', 0, 'subscription document, Sub doc, subdoc, subscription doc, Sub docs, subdocs, subscription docs, sub-doc, sub documents, subscription file'),
        ('DocType', 'Tax Statement', 'TAX', 'Statements', 'STM', 'Months', 0, 'K1, Schedule K1, K-1, Schedule K-1, tax info, tax filings, Form 5471, Pro-forma 5471, 5471 filing, 5471, K1 Statement, K-1 Statement, 5471 statement, Tax statement, tax statement, tax info, 5471 filing, Tax, PFIC, PFIC Statement'),
        ('DocType', 'Trade Instruction', 'TRADE', 'Agreements', 'AGR', 'Years', 0, 'Trade Authorization'),
        ('DocType', 'Valuation Policy', 'VPA', 'Agreements', 'AGR', 'Years', 0, 'valuation policies'),
        ('DocType', 'White Paper', 'WHTP', 'General', 'GEN', 'Months', 0, 'article'),
        ('Economy', 'All-market', 'ALL', null, null, null, 0, 'All-market'),
        ('Economy', 'Developed', 'DEV', null, null, null, 0, 'Developed'),
        ('Economy', 'Emerging', 'EM', null, null, null, 0, 'developing markets'),
        ('Economy', 'Frontier', 'FR', null, null, null, 0, 'Frontier'),
        ('Exposure', 'Directional', 'DIR', null, null, null, 0, 'Directional'),
        ('Exposure', 'Long Bias', 'LONG', null, null, null, 0, 'Long Only'),
        ('Exposure', 'Market Neutral', 'MN', null, null, null, 0, 'Low Net, Absolute Return, market-neutral'),
        ('Exposure', 'Short Bias', 'SHORT', null, null, null, 0, 'Short Bias, net-short'),
        ('FILETYPE', 'Pdf', 'PDF', null, null, null, 0, null),
        ('FILETYPE', 'Presentation', 'PPTX', null, null, null, 0, null),
        ('FILETYPE', 'Spreadsheet', 'XLSX', null, null, null, 0, null),
        ('FILETYPE', 'WordDocument', 'DOCX', null, null, null, 0, null),
        ('FLAG', 'Entity Owner', 'ENTITY', null, null, null, 1, 'Entity Owner'),
        ('FLAG', 'High Interest', 'HIGH', null, null, null, 1, 'High Interest'),
        ('FLAG', 'Low Interest', 'LOW', null, null, null, 1, 'Low Interest'),
        ('FLAG', 'Negative Sentiment', 'NEG', null, null, null, 1, 'Negative Sentiment'),
        ('FLAG', 'Positive Sentiment', 'POS', null, null, null, 1, 'Positive Sentiment'),
        ('LABELS', 'Class', 'AC', null, null, null, 1, 'asset-class, asset class'),
        ('LABELS', 'Concept', 'CONCEPT', null, null, null, 1, 'Concept'),
        ('LABELS', 'File Name', 'FN', null, null, null, 1, 'File Name'),
        ('LABELS', 'Fund Ticker', 'ID', null, null, null, 1, 'Fund Ticker'),
        ('LABELS', 'System Tags', 'STAG', null, null, null, 1, ''),
        ('LABELS', 'Tag', 'TAG', null, null, null, 1, 'Tag'),
        ('MarketCap', 'All-cap', 'ACAP', null, null, null, 0, 'All Cap, All-cap'),
        ('MarketCap', 'Large', 'LARGE', null, null, null, 0, 'Large Cap, Large-cap'),
        ('MarketCap', 'Mega', 'MEGA', null, null, null, 0, 'Mega Cap,Mega-cap'),
        ('MarketCap', 'Micro', 'MICRO', null, null, null, 0, 'Micro Cap, Micro-cap'),
        ('MarketCap', 'Mid', 'MID', null, null, null, 0, 'Mid Cap,Mid-cap'),
        ('MarketCap', 'Small', 'SMALL', null, null, null, 0, 'Small Cap'),
        ('Private Market Structure and Class Equities Combination', 'Private Credit', 'PC', null, null, null, 0, 'Private Credit'),
        ('Private Market Structure and Class Equities Combination', 'Private Equity', 'PE', null, null, null, 0, 'Private Equity'),
        ('Region', 'Africa', 'AF', null, null, null, 0, 'Africa'),
        ('Region', 'Asia', 'ASIA', null, null, null, 0, 'asian, japan, japanese, china, chinese, pan-asia'),
        ('Region', 'Europe', 'EU', null, null, null, 0, 'European Union, Western Europe, european, uk, u.k., united kingdom, great britain, france, germany, spain, italy, switzerland, EEMA, eastern europe'),
        ('Region', 'Global', 'G', null, null, null, 0, null),
        ('Region', 'Latin America', 'LAT', null, null, null, 0, 'LatAm, Lat Am, South America, latin american'),
        ('Region', 'Middle East', 'MENA', null, null, null, 0, 'EEMA'),
        ('Region', 'North America', 'US', null, null, null, 0, 'U.S., USA, United States, NA'),
        ('Sector', 'Consumer', 'C', null, null, null, 0, 'Consumer'),
        ('Sector', 'Energy', 'E', null, null, null, 0, 'Energy'),
        ('Sector', 'Financials', 'F', null, null, null, 0, 'Financials'),
        ('Sector', 'Healthcare', 'H', null, null, null, 0, 'Healthcare'),
        ('Sector', 'Industrials', 'I', null, null, null, 0, 'Industrials'),
        ('Sector', 'Materials', 'MAT', null, null, null, 0, 'Materials'),
        ('Sector', 'Multi-Sector', 'S', null, null, null, 0, 'Multi-Sector'),
        ('Sector', 'Technology', 'T', null, null, null, 0, 'TMT'),
        ('Sector', 'Utilities', 'UT', null, null, null, 0, 'Utilities, UTL'),
        ('Source', 'Administrator', 'ADM', null, null, null, 0, 'Admin'),
        ('Source', 'Asset Manager', 'AM', null, null, null, 0, 'IM, Investment manager, Buy side'),
        ('Source', 'Asset Owner', 'AO', null, null, null, 0, 'AssetOwner'),
        ('Source', 'Auditor', 'AU', null, null, null, 0, 'Auditor'),
        ('Source', 'Bank', 'BN', null, null, null, 0, 'Custodian, House views, Prop research, Sell side, prop desk, prop-desk, propdesk'),
        ('Source', 'Broker', 'BRK', null, null, null, 0, 'Prime broker, Sell side'),
        ('Source', 'Consultant', 'CNSLT', null, null, null, 0, 'External Research'),
        ('Source', 'Legal Counsel', 'LC', null, null, null, 0, 'Law Firm, Lawyer'),
        ('Source', 'Press', 'PRS', null, null, null, 0, 'Publisher, Journal'),
        ('Specialty', 'Activist', 'ACT', null, null, null, 0, 'Activist'),
        ('Specialty', 'Asset Backed', 'AB', null, null, null, 0, 'Asset-backed'),
        ('Specialty', 'Capital Structure Arbitrage', 'CAPS', null, null, null, 0, 'Cap Structure Arb'),
        ('Specialty', 'Convertible Arbitrage', 'CB', null, null, null, 0, 'Convert Arb'),
        ('Specialty', 'Corporate Debt', 'CORPB', null, null, null, 0, 'Corporates, IG, corporate bond'),
        ('Specialty', 'Currency', 'FX', null, null, null, 0, 'Currency Trading, Currency Traders, FX Trading'),
        ('Specialty', 'Distressed', 'DS', null, null, null, 0, 'Distressed Debt'),
        ('Specialty', 'Fundamental', 'FU', null, null, null, 0, 'Fundamental'),
        ('Specialty', 'High Yield Debt', 'HY', null, null, null, 0, 'High Yield'),
        ('Specialty', 'Hybrid Debt', 'HYB', null, null, null, 0, 'Hybrid Debt'),
        ('Specialty', 'Merger Arbitrage', 'MA', null, null, null, 0, 'Merger Arb'),
        ('Specialty', 'Multi-Specialty', 'MSP', null, null, null, 0, ''),
        ('Specialty', 'Sovereign Debt', 'SOV', null, null, null, 0, 'Sovereigns, sovereign debt, sovereign debts'),
        ('Specialty', 'Systematic', 'SYS', null, null, null, 0, 'Systematic Trading, Quant Trading, Quants, Quant, Quantitative Trading, Statistical Arbitrage, Stat Arb'),
        ('Specialty', 'Thematic', 'THM', null, null, null, 0, null),
        ('Specialty', 'Volatility Arbitrage', 'VOL', null, null, null, 0, 'Vol Arb, volatility arbitrage'),
        ('Strategy', 'Buyout', 'BO', null, null, null, 0, 'Buyout'),
        ('Strategy', 'Co-Investment', 'CO', null, null, null, 0, 'coinvest'),
        ('Strategy', 'Event Driven', 'ED', null, null, null, 0, 'Event-Driven'),
        ('Strategy', 'Hedge Equity', 'HEQ', null, null, null, 0, 'Long/Short Equity, Long Short Equity, Long-short Equity, LS Equity, L/S Equity, Equity Hedge, Hedged Equity'),
        ('Strategy', 'Hedge Fixed Income', 'HFI', null, null, null, 0, 'Long/Short Credit, Long Short Credit, Long-short Credit, Long Short FI, Long/Short FI, Fixed Income Hedge, FI Hedge, Fixed-Income Hedge, Long Short Fixed Income'),
        ('Strategy', 'Macro', 'MC', null, null, null, 1, 'Macro Trading, trading, CTA'),
        ('Strategy', 'Multi-Strategy', 'MS', null, null, null, 1, 'Multi-Strat, Multi-Strategy, multistrategy, multistrat, multi strat'),
        ('Strategy', 'Relative Value', 'RV', null, null, null, 1, 'RV, Relative Value'),
        ('Strategy', 'Secondary', 'SD', null, null, null, 0, 'Secondaries'),
        ('Strategy', 'Special Situations', 'CS', null, null, null, 1, 'Special Sits, Special Sit'),
        ('Strategy', 'Venture Capital', 'VC', null, null, null, 0, 'Venture Cap, vulture fund'),
        ('Structure', 'Hedge Fund', 'HF', null, null, null, 0, 'hedged, alternative fund, flexible capital'),
        ('Structure', 'OTHER', 'STR_OTHER', null, null, null, 0, 'RS, research, AC_OTHER'),
        ('Structure', 'Private Markets', 'PRM', null, null, null, 0, 'Privates, PM'),
        ('Structure', 'Public Markets', 'PBM', null, null, null, 0, 'Long-Only, Mutual Fund, MF'),
        ('Structure', 'Real Assets', 'RA', null, null, null, 0, 'Real-Assets'),
        ('Subsector', 'Agriculture', 'AG', null, null, null, 0, 'Agriculture'),
        ('Subsector', 'Biotech', 'BIO', null, null, null, 0, 'Biotechnology'),
        ('Subsector', 'Insurance', 'INSUR', null, null, null, 0, 'Insurance'),
        ('Subsector', 'Media', 'MEDIA', null, null, null, 0, 'Media'),
        ('Subsector', 'Mining', 'MINING', null, null, null, 0, 'Mining'),
        ('Subsector', 'MLPs', 'MLP', null, null, null, 0, 'Master Limited Partnerships'),
        ('Subsector', 'Real Estate', 'RE', null, null, null, 0, 'Real Estate, REAL'),
        ('Subsector', 'Resources', 'RES', null, null, null, 0, 'Natural Resources'),
        ('Subsector', 'Shipping', 'SHIP', null, null, null, 0, 'Shipping, SHP'),
        ('Subsector', 'Telecom', 'TELE', null, null, null, 0, 'Telecommunications, telco, teleco');